// Smart Contract ABI for UniversityDegreeProtocol V2
// New contract with Verifier Stage functionality
// Core Contract Address: 0xBb51Dc84f0b35d3344f777543CA6549F9427B313

export const PROTOCOL_ABI_V2 = [
  // View Functions
  {
    inputs: [],
    name: "name",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "symbol",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "nextUniversityId",
    outputs: [{ internalType: "uint64", name: "", type: "uint64" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "nextTokenId",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "nextDegreeRequestId",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "nextRevocationRequestId",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "totalSupply",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint64", name: "", type: "uint64" }],
    name: "universities",
    outputs: [
      { internalType: "address", name: "admin", type: "address" },
      { internalType: "string", name: "nameAr", type: "string" },
      { internalType: "string", name: "nameEn", type: "string" },
      { internalType: "bool", name: "exists", type: "bool" },
      { internalType: "bool", name: "isActive", type: "bool" },
      { internalType: "bool", name: "isDeleted", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
    name: "tokenURI",
    outputs: [{ internalType: "string", name: "", type: "string" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
    name: "ownerOf",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "owner_", type: "address" }],
    name: "balanceOf",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint64", name: "universityId", type: "uint64" }],
    name: "getUniversity",
    outputs: [
      {
        components: [
          { internalType: "address", name: "admin", type: "address" },
          { internalType: "string", name: "nameAr", type: "string" },
          { internalType: "string", name: "nameEn", type: "string" },
          { internalType: "bool", name: "exists", type: "bool" },
          { internalType: "bool", name: "isActive", type: "bool" },
          { internalType: "bool", name: "isDeleted", type: "bool" },
        ],
        internalType: "struct UniversityDegreeProtocol.University",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
    name: "getDegree",
    outputs: [
      {
        components: [
          { internalType: "uint64", name: "universityId", type: "uint64" },
          { internalType: "uint16", name: "gpa", type: "uint16" },
          { internalType: "uint16", name: "year", type: "uint16" },
          { internalType: "bool", name: "isRevoked", type: "bool" },
          { internalType: "uint40", name: "issuedAt", type: "uint40" },
          { internalType: "uint40", name: "revokedAt", type: "uint40" },
          { internalType: "string", name: "nameAr", type: "string" },
          { internalType: "string", name: "nameEn", type: "string" },
          { internalType: "string", name: "facultyAr", type: "string" },
          { internalType: "string", name: "facultyEn", type: "string" },
          { internalType: "string", name: "majorAr", type: "string" },
          { internalType: "string", name: "majorEn", type: "string" },
          { internalType: "string", name: "degreeNameAr", type: "string" },
          { internalType: "string", name: "degreeNameEn", type: "string" },
        ],
        internalType: "struct UniversityDegreeProtocol.Degree",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
    name: "isValidDegree",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint64", name: "universityId", type: "uint64" },
      { internalType: "address", name: "account", type: "address" },
    ],
    name: "isIssuer",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint64", name: "universityId", type: "uint64" },
      { internalType: "address", name: "account", type: "address" },
    ],
    name: "isRevoker",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint64", name: "universityId", type: "uint64" },
      { internalType: "address", name: "verifier", type: "address" },
    ],
    name: "isVerifier",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint64", name: "universityId", type: "uint64" }],
    name: "getUniversityVerifiers",
    outputs: [{ internalType: "address[]", name: "", type: "address[]" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint64", name: "universityId", type: "uint64" }],
    name: "getRequiredApprovals",
    outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint64", name: "universityId", type: "uint64" }],
    name: "verifierCount",
    outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "requestId", type: "uint256" }],
    name: "getDegreeRequest",
    outputs: [
      {
        components: [
          { internalType: "uint64", name: "universityId", type: "uint64" },
          { internalType: "address", name: "recipient", type: "address" },
          { internalType: "address", name: "requester", type: "address" },
          { internalType: "uint16", name: "gpa", type: "uint16" },
          { internalType: "uint16", name: "year", type: "uint16" },
          { internalType: "uint8", name: "approvalCount", type: "uint8" },
          { internalType: "uint40", name: "createdAt", type: "uint40" },
          { internalType: "bool", name: "executed", type: "bool" },
          { internalType: "bool", name: "rejected", type: "bool" },
          { internalType: "string", name: "nameAr", type: "string" },
          { internalType: "string", name: "nameEn", type: "string" },
          { internalType: "string", name: "facultyAr", type: "string" },
          { internalType: "string", name: "facultyEn", type: "string" },
          { internalType: "string", name: "majorAr", type: "string" },
          { internalType: "string", name: "majorEn", type: "string" },
          { internalType: "string", name: "degreeNameAr", type: "string" },
          { internalType: "string", name: "degreeNameEn", type: "string" },
        ],
        internalType: "struct UniversityDegreeProtocol.DegreeRequest",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "requestId", type: "uint256" }],
    name: "getRevocationRequest",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "tokenId", type: "uint256" },
          { internalType: "uint64", name: "universityId", type: "uint64" },
          { internalType: "address", name: "requester", type: "address" },
          { internalType: "uint8", name: "approvalCount", type: "uint8" },
          { internalType: "uint40", name: "createdAt", type: "uint40" },
          { internalType: "bool", name: "executed", type: "bool" },
          { internalType: "bool", name: "rejected", type: "bool" },
        ],
        internalType: "struct UniversityDegreeProtocol.RevocationRequest",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "requestId", type: "uint256" },
      { internalType: "address", name: "verifier", type: "address" },
    ],
    name: "hasApprovedDegreeRequest",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "requestId", type: "uint256" },
      { internalType: "address", name: "verifier", type: "address" },
    ],
    name: "hasApprovedRevocationRequest",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "view",
    type: "function",
  },
  // Owner Functions
  {
    inputs: [
      { internalType: "address", name: "admin", type: "address" },
      { internalType: "string", name: "nameAr", type: "string" },
      { internalType: "string", name: "nameEn", type: "string" },
    ],
    name: "registerUniversity",
    outputs: [{ internalType: "uint64", name: "id", type: "uint64" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint64", name: "universityId", type: "uint64" },
      { internalType: "bool", name: "isActive", type: "bool" },
    ],
    name: "setUniversityStatus",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint64", name: "universityId", type: "uint64" }],
    name: "deleteUniversity",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint64", name: "universityId", type: "uint64" },
      { internalType: "address", name: "newAdmin", type: "address" },
    ],
    name: "updateUniversityAdmin",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "newRenderer", type: "address" }],
    name: "setRenderer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  // University Admin Functions
  {
    inputs: [
      { internalType: "uint64", name: "universityId", type: "uint64" },
      { internalType: "address", name: "issuer", type: "address" },
    ],
    name: "grantIssuer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint64", name: "universityId", type: "uint64" },
      { internalType: "address", name: "issuer", type: "address" },
    ],
    name: "revokeIssuer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint64", name: "universityId", type: "uint64" },
      { internalType: "address", name: "revoker", type: "address" },
    ],
    name: "grantRevoker",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint64", name: "universityId", type: "uint64" },
      { internalType: "address", name: "revoker", type: "address" },
    ],
    name: "revokeRevoker",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint64", name: "universityId", type: "uint64" },
      { internalType: "address", name: "verifier", type: "address" },
    ],
    name: "addVerifier",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint64", name: "universityId", type: "uint64" },
      { internalType: "address", name: "verifier", type: "address" },
    ],
    name: "removeVerifier",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  // Issuer Functions (New Verifier Stage Flow)
  {
    inputs: [
      { internalType: "uint64", name: "universityId", type: "uint64" },
      { internalType: "address", name: "recipient", type: "address" },
      { internalType: "string", name: "nameAr", type: "string" },
      { internalType: "string", name: "nameEn", type: "string" },
      { internalType: "string", name: "facultyAr", type: "string" },
      { internalType: "string", name: "facultyEn", type: "string" },
      { internalType: "string", name: "majorAr", type: "string" },
      { internalType: "string", name: "majorEn", type: "string" },
      { internalType: "string", name: "degreeNameAr", type: "string" },
      { internalType: "string", name: "degreeNameEn", type: "string" },
      { internalType: "uint16", name: "gpa", type: "uint16" },
      { internalType: "uint16", name: "year", type: "uint16" },
    ],
    name: "requestDegree",
    outputs: [{ internalType: "uint256", name: "requestId", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  // Verifier Functions
  {
    inputs: [{ internalType: "uint256", name: "requestId", type: "uint256" }],
    name: "approveDegreeRequest",
    outputs: [{ internalType: "bool", name: "issued", type: "bool" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "requestId", type: "uint256" }],
    name: "rejectDegreeRequest",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  // Revoker Functions (New Verifier Stage Flow)
  {
    inputs: [{ internalType: "uint256", name: "tokenId", type: "uint256" }],
    name: "requestRevocation",
    outputs: [{ internalType: "uint256", name: "requestId", type: "uint256" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  // Verifier Functions for Revocation
  {
    inputs: [{ internalType: "uint256", name: "requestId", type: "uint256" }],
    name: "approveRevocationRequest",
    outputs: [{ internalType: "bool", name: "revoked", type: "bool" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "requestId", type: "uint256" }],
    name: "rejectRevocationRequest",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  // Events
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "from", type: "address" },
      { indexed: true, internalType: "address", name: "to", type: "address" },
      { indexed: true, internalType: "uint256", name: "tokenId", type: "uint256" },
    ],
    name: "Transfer",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint64", name: "universityId", type: "uint64" },
      { indexed: false, internalType: "string", name: "nameEn", type: "string" },
      { indexed: false, internalType: "address", name: "admin", type: "address" },
    ],
    name: "UniversityRegistered",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint64", name: "universityId", type: "uint64" },
      { indexed: false, internalType: "bool", name: "isActive", type: "bool" },
    ],
    name: "UniversityStatusChanged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint64", name: "universityId", type: "uint64" },
      { indexed: false, internalType: "address", name: "newAdmin", type: "address" },
    ],
    name: "UniversityAdminChanged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: "uint64", name: "universityId", type: "uint64" }],
    name: "UniversityDeleted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint64", name: "universityId", type: "uint64" },
      { indexed: true, internalType: "address", name: "issuer", type: "address" },
      { indexed: false, internalType: "bool", name: "status", type: "bool" },
    ],
    name: "IssuerUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint64", name: "universityId", type: "uint64" },
      { indexed: true, internalType: "address", name: "revoker", type: "address" },
      { indexed: false, internalType: "bool", name: "status", type: "bool" },
    ],
    name: "RevokerUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint64", name: "universityId", type: "uint64" },
      { indexed: true, internalType: "address", name: "verifier", type: "address" },
    ],
    name: "VerifierAdded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint64", name: "universityId", type: "uint64" },
      { indexed: true, internalType: "address", name: "verifier", type: "address" },
    ],
    name: "VerifierRemoved",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "requestId", type: "uint256" },
      { indexed: true, internalType: "uint64", name: "universityId", type: "uint64" },
      { indexed: true, internalType: "address", name: "recipient", type: "address" },
      { indexed: false, internalType: "address", name: "requester", type: "address" },
    ],
    name: "DegreeRequested",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "requestId", type: "uint256" },
      { indexed: true, internalType: "address", name: "verifier", type: "address" },
      { indexed: false, internalType: "uint8", name: "currentApprovals", type: "uint8" },
      { indexed: false, internalType: "uint8", name: "required", type: "uint8" },
    ],
    name: "DegreeRequestApproved",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "requestId", type: "uint256" },
      { indexed: true, internalType: "address", name: "verifier", type: "address" },
    ],
    name: "DegreeRequestRejected",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "tokenId", type: "uint256" },
      { indexed: true, internalType: "uint64", name: "universityId", type: "uint64" },
      { indexed: true, internalType: "address", name: "recipient", type: "address" },
      { indexed: false, internalType: "uint256", name: "requestId", type: "uint256" },
    ],
    name: "DegreeIssued",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "requestId", type: "uint256" },
      { indexed: true, internalType: "uint256", name: "tokenId", type: "uint256" },
      { indexed: true, internalType: "uint64", name: "universityId", type: "uint64" },
      { indexed: false, internalType: "address", name: "requester", type: "address" },
    ],
    name: "RevocationRequested",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "requestId", type: "uint256" },
      { indexed: true, internalType: "address", name: "verifier", type: "address" },
      { indexed: false, internalType: "uint8", name: "currentApprovals", type: "uint8" },
      { indexed: false, internalType: "uint8", name: "required", type: "uint8" },
    ],
    name: "RevocationApproved",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "requestId", type: "uint256" },
      { indexed: true, internalType: "address", name: "verifier", type: "address" },
    ],
    name: "RevocationRejected",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "tokenId", type: "uint256" },
      { indexed: true, internalType: "uint64", name: "universityId", type: "uint64" },
      { indexed: false, internalType: "uint256", name: "requestId", type: "uint256" },
    ],
    name: "DegreeRevoked",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "address", name: "oldRenderer", type: "address" },
      { indexed: true, internalType: "address", name: "newRenderer", type: "address" },
    ],
    name: "RendererUpdated",
    type: "event",
  },
] as const
